<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SyncMetrics.Pipeline.Core\SyncMetrics.Pipeline.Core.csproj" />
    <ProjectReference Include="..\SyncMetrics.Pipeline.Application\SyncMetrics.Pipeline.Application.csproj" />
    <ProjectReference Include="..\SyncMetrics.Pipeline.Infrastructure\SyncMetrics.Pipeline.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.*" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SyncMetrics.Pipeline.Console</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
